import { type DashboardTemplate } from '@/dashboards/templates/types/DashboardTemplate';
import { AggregateOperations } from '~/generated-metadata/graphql';

const XOPURE_LIVE_METRIC_COUNTER_FRONT_COMPONENT_UNIVERSAL_IDENTIFIER =
  'b2cac5d7-b9b7-4fcb-89de-3c9a264b866d';
const XOPURE_REALTIME_REVENUE_LINE_CHART_FRONT_COMPONENT_UNIVERSAL_IDENTIFIER =
  '17b51f1d-24dd-4fc5-b62f-07b3d168f361';
const XOPURE_LIVE_ACTIVITY_FEED_FRONT_COMPONENT_UNIVERSAL_IDENTIFIER =
  '41f61b3b-ab7a-44df-a22e-4bb62f58021e';

// 12-column grid. Charts default to 6 wide x 6 tall; tables span the full width.
// Object/field names are resolved per-workspace at instantiation; any widget whose
// object does not exist in the current workspace is skipped, so a template never
// produces broken widgets.

const fullWidthRow = (row: number) => ({
  row,
  column: 0,
  rowSpan: 6,
  columnSpan: 12,
});

const leftHalf = (row: number) => ({
  row,
  column: 0,
  rowSpan: 6,
  columnSpan: 6,
});

const rightHalf = (row: number) => ({
  row,
  column: 6,
  rowSpan: 6,
  columnSpan: 6,
});

// Quarter-width KPI cards: four across on the 12-column grid (columnSpan 3).
const quarter = (row: number, index: number) => ({
  row,
  column: index * 3,
  rowSpan: 6,
  columnSpan: 3,
});

export const AMBASSADOR_GROWTH_TEMPLATE: DashboardTemplate = {
  key: 'ambassador-growth',
  name: 'Ambassador Growth',
  description:
    'Track ambassador sign-ups, downline growth, and commission performance over time.',
  icon: 'IconUsersGroup',
  tabs: [
    {
      title: 'Overview',
      icon: 'IconChartArcs',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Ambassadors',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Group CV',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'groupCV',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Lifetime Earnings',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'lifetimeEarnings',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Active Customers',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'activeCustomerCount',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 3),
        },
        {
          type: 'graph',
          visualization: 'line',
          title: 'New Ambassadors Over Time',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'enrolledAt',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Ambassadors by Status',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'status',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(6),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Ambassadors by Paid-As Rank',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'paidAsRank',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Commission Tier Mix',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'currentTier',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Ambassadors by Path',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'path',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(18),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Elite Maintained Share',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'eliteMaintained',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(18),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Onboarding Stage',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'onboardingStage',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: fullWidthRow(24),
        },
        {
          type: 'recordTable',
          title: 'Recent Ambassadors',
          objectNameSingular: 'ambassador',
          gridPosition: fullWidthRow(30),
        },
      ],
    },
  ],
};

export const CUSTOMER_360_TEMPLATE: DashboardTemplate = {
  key: 'customer-360',
  name: 'Customer 360',
  description:
    'A complete view of XO Pure customers, growth, subscription status, and recent activity.',
  icon: 'IconUsers',
  tabs: [
    {
      title: 'Overview',
      icon: 'IconLayoutDashboard',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Customers',
          objectNameSingular: 'customer',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Lifetime Spend',
          objectNameSingular: 'customer',
          aggregateFieldName: 'lifetimeSpend',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Lifetime CV',
          objectNameSingular: 'customer',
          aggregateFieldName: 'lifetimeCV',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Orders per Customer',
          objectNameSingular: 'customer',
          aggregateFieldName: 'orderCount',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 3),
        },
        {
          type: 'graph',
          visualization: 'line',
          title: 'Customer Growth',
          objectNameSingular: 'customer',
          groupByFieldName: 'enrolledAt',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Customers by Subscription',
          objectNameSingular: 'customer',
          groupByFieldName: 'subscriptionStatus',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Customers by Acquisition Source',
          objectNameSingular: 'customer',
          groupByFieldName: 'acquisitionSource',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Active vs Inactive Customers',
          objectNameSingular: 'customer',
          groupByFieldName: 'isActive',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(12),
        },
        {
          type: 'recordTable',
          title: 'Recent Customers',
          objectNameSingular: 'customer',
          gridPosition: fullWidthRow(18),
        },
      ],
    },
  ],
};

export const REVENUE_AND_ORDERS_TEMPLATE: DashboardTemplate = {
  key: 'revenue-and-orders',
  name: 'Revenue & Orders',
  description:
    'Monitor order volume, revenue trends, and pipeline value across the business.',
  icon: 'IconCoin',
  tabs: [
    {
      title: 'Revenue',
      icon: 'IconTrendingUp',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Revenue',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'totalRetail',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total CV',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'totalCV',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Orders',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Average Order Value',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'totalRetail',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 3),
        },
        {
          type: 'graph',
          visualization: 'line',
          title: 'Revenue Over Time',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'orderedAt',
          aggregateFieldName: 'totalRetail',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Orders Over Time',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'orderedAt',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Orders by Status',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'status',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Orders by Payment Method',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'paymentMethod',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Self-Referral (Personal Order) Share',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'isPersonalOrder',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(18),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Units Sold',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'quantity',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: rightHalf(18),
        },
        {
          type: 'recordTable',
          title: 'Recent Orders',
          objectNameSingular: 'xoOrder',
          gridPosition: fullWidthRow(24),
        },
      ],
    },
  ],
};

export const LIVE_OPERATIONS_TEMPLATE: DashboardTemplate = {
  key: 'live-operations',
  name: 'Live Operations',
  description:
    'Operational snapshot of recent orders and activity with optional read-only Supabase Realtime cards.',
  icon: 'IconActivityHeartbeat',
  tabs: [
    {
      title: 'Operations',
      icon: 'IconActivity',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Orders',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(0),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Orders by Status',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'status',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(0),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Orders Over Time',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'orderedAt',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: fullWidthRow(6),
        },
        {
          type: 'frontComponent',
          title: 'Live Supabase Order Count',
          frontComponentUniversalIdentifier:
            XOPURE_LIVE_METRIC_COUNTER_FRONT_COMPONENT_UNIVERSAL_IDENTIFIER,
          gridPosition: fullWidthRow(12),
        },
        {
          type: 'frontComponent',
          title: 'Realtime Revenue Trend',
          frontComponentUniversalIdentifier:
            XOPURE_REALTIME_REVENUE_LINE_CHART_FRONT_COMPONENT_UNIVERSAL_IDENTIFIER,
          gridPosition: fullWidthRow(18),
        },
        {
          type: 'frontComponent',
          title: 'Live Order Activity',
          frontComponentUniversalIdentifier:
            XOPURE_LIVE_ACTIVITY_FEED_FRONT_COMPONENT_UNIVERSAL_IDENTIFIER,
          gridPosition: fullWidthRow(24),
        },
        {
          type: 'recordTable',
          title: 'Latest Orders',
          objectNameSingular: 'xoOrder',
          gridPosition: fullWidthRow(30),
        },
      ],
    },
  ],
};

// Admin "Mission Control I — Growth & Revenue": the global command center. Every card
// resolves on the native engine over already-synced fields (no relation group-by, filters,
// or front components), so the dashboard renders complete on first instantiation.
// See docs/xopure-admin-and-portal-dashboards.md §1A.
export const ADMIN_MISSION_CONTROL_I_TEMPLATE: DashboardTemplate = {
  key: 'admin-mission-control-i',
  name: 'Admin · Mission Control I — Growth & Revenue',
  description:
    'The owner/ops command center: headline revenue and CV, growth trends, order and acquisition breakdowns, and top performers at a glance.',
  icon: 'IconLayoutDashboard',
  tabs: [
    {
      title: 'Growth & Revenue',
      icon: 'IconTrendingUp',
      widgets: [
        // KPI row
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Revenue',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'totalRetail',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total CV',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'totalCV',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Ambassadors',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Customers',
          objectNameSingular: 'customer',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 3),
        },
        // Trends
        {
          type: 'graph',
          visualization: 'line',
          title: 'Revenue Over Time',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'orderedAt',
          aggregateFieldName: 'totalRetail',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Orders Over Time',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'orderedAt',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(6),
        },
        // Breakdowns
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Orders by Status',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'status',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Customers by Acquisition Source',
          objectNameSingular: 'customer',
          groupByFieldName: 'acquisitionSource',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(12),
        },
        // Secondary
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Average Order Value',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'totalRetail',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: leftHalf(18),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Orders by Payment Method',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'paymentMethod',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(18),
        },
        // Tables
        {
          type: 'recordTable',
          title: 'Top Ambassadors',
          objectNameSingular: 'ambassador',
          gridPosition: fullWidthRow(24),
        },
        {
          type: 'recordTable',
          title: 'Recent Orders',
          objectNameSingular: 'xoOrder',
          gridPosition: fullWidthRow(30),
        },
      ],
    },
  ],
};

// Admin "Mission Control II — Compensation & Network": the comp/structure command center.
// All cards are native: period & ambassador aggregates, SELECT/DATE/BOOLEAN group-bys, and
// record tables. Held/payable, sweep eligibility, and the downline tree remain pending on
// derived comp data / a new primitive — see docs/xopure-admin-and-portal-dashboards.md §1B.
export const ADMIN_MISSION_CONTROL_II_TEMPLATE: DashboardTemplate = {
  key: 'admin-mission-control-ii',
  name: 'Admin · Mission Control II — Compensation & Network',
  description:
    'Compensation cost and field structure: period payouts and trends, rank and tier distribution, elite health, and ambassador network composition.',
  icon: 'IconCoins',
  tabs: [
    {
      title: 'Compensation',
      icon: 'IconCoin',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Payouts',
          objectNameSingular: 'period',
          aggregateFieldName: 'totalPayouts',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total CV (periods)',
          objectNameSingular: 'period',
          aggregateFieldName: 'totalCV',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Retail (periods)',
          objectNameSingular: 'period',
          aggregateFieldName: 'totalRetail',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Lifetime Comp Paid',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'lifetimeEarnings',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 3),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Payouts by Period',
          objectNameSingular: 'period',
          groupByFieldName: 'endDate',
          aggregateFieldName: 'totalPayouts',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'line',
          title: 'Payout % of Retail Trend',
          objectNameSingular: 'period',
          groupByFieldName: 'endDate',
          aggregateFieldName: 'payoutPercentOfRetail',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: rightHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Periods by Status',
          objectNameSingular: 'period',
          groupByFieldName: 'status',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(12),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Ambassadors by Paid-As Rank',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'paidAsRank',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Commission Tier Mix',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'currentTier',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(18),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Lifetime Earnings',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'lifetimeEarnings',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: rightHalf(18),
        },
        {
          type: 'recordTable',
          title: 'Periods',
          objectNameSingular: 'period',
          gridPosition: fullWidthRow(24),
        },
      ],
    },
    {
      title: 'Network',
      icon: 'IconUsersGroup',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Ambassadors',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Group CV',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'groupCV',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Active Customers',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'activeCustomerCount',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Personal Enrollments',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'personalEnrollments',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 3),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Ambassadors by Path',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'path',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Ambassadors by Qualified Rank',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'qualifiedRank',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Elite Maintained Share',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'eliteMaintained',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Ambassadors by Status',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'status',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(12),
        },
        {
          type: 'recordTable',
          title: 'Ambassadors',
          objectNameSingular: 'ambassador',
          gridPosition: fullWidthRow(18),
        },
      ],
    },
  ],
};

// "Compliance & Risk Command": fraud, refunds/chargebacks, self-referral integrity. Native —
// status/payment/boolean group-bys plus a fraud-score gauge (now that the gauge router renders).
export const COMPLIANCE_AND_RISK_TEMPLATE: DashboardTemplate = {
  key: 'compliance-and-risk',
  name: 'Compliance & Risk Command',
  description:
    'Monitor fraud scoring, refunds and chargebacks, self-referral integrity, and payment-method exposure across orders.',
  icon: 'IconShieldCheck',
  tabs: [
    {
      title: 'Risk',
      icon: 'IconShieldCheck',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Orders',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Fraud Score',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'fraudScore',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total CV',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'totalCV',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Revenue',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'totalRetail',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 3),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Orders by Status',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'status',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Fraud-Flagged Share',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'fraudFlagged',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Self-Referral (Personal Order) Share',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'isPersonalOrder',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Orders by Payment Method',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'paymentMethod',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(12),
        },
        {
          type: 'graph',
          visualization: 'gauge',
          title: 'Avg Fraud Score (0–100)',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'fraudScore',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: leftHalf(18),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Max Fraud Score',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'fraudScore',
          aggregateOperation: AggregateOperations.MAX,
          gridPosition: rightHalf(18),
        },
        {
          type: 'recordTable',
          title: 'Orders',
          objectNameSingular: 'xoOrder',
          gridPosition: fullWidthRow(24),
        },
      ],
    },
  ],
};

// "Recruiting & Onboarding": ambassador & customer acquisition plus the onboarding-stage funnel
// (rendered as a bar until a funnel primitive exists). All native.
export const RECRUITING_AND_ONBOARDING_TEMPLATE: DashboardTemplate = {
  key: 'recruiting-and-onboarding',
  name: 'Recruiting & Onboarding',
  description:
    'Track ambassador and customer acquisition, onboarding-stage progression, acquisition sources, and enrollment momentum.',
  icon: 'IconUserPlus',
  tabs: [
    {
      title: 'Recruiting & Onboarding',
      icon: 'IconUserPlus',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Ambassadors',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Customers',
          objectNameSingular: 'customer',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Personal Enrollments',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'personalEnrollments',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Active Customers',
          objectNameSingular: 'ambassador',
          aggregateFieldName: 'activeCustomerCount',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 3),
        },
        {
          type: 'graph',
          visualization: 'line',
          title: 'New Ambassadors Over Time',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'enrolledAt',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'line',
          title: 'New Customers Over Time',
          objectNameSingular: 'customer',
          groupByFieldName: 'enrolledAt',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(6),
        },
        {
          type: 'graph',
          visualization: 'bar',
          title: 'Onboarding Stage Funnel',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'onboardingStage',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: fullWidthRow(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Customers by Acquisition Source',
          objectNameSingular: 'customer',
          groupByFieldName: 'acquisitionSource',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(18),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Ambassadors by Path',
          objectNameSingular: 'ambassador',
          groupByFieldName: 'path',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(18),
        },
        {
          type: 'recordTable',
          title: 'Ambassadors',
          objectNameSingular: 'ambassador',
          gridPosition: fullWidthRow(24),
        },
      ],
    },
  ],
};

// "Product Performance": catalog composition, pricing/CV, and units sold. Native — product-object
// group-bys (no relation group-by) plus order quantity/value aggregates.
export const PRODUCT_PERFORMANCE_TEMPLATE: DashboardTemplate = {
  key: 'product-performance',
  name: 'Product Performance',
  description:
    'Catalog health and sales: product mix by category and format, pricing and CV, commission eligibility, and units sold.',
  icon: 'IconPackage',
  tabs: [
    {
      title: 'Catalog & Sales',
      icon: 'IconPackage',
      widgets: [
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Products',
          objectNameSingular: 'product',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: quarter(0, 0),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Retail Price',
          objectNameSingular: 'product',
          aggregateFieldName: 'retailPrice',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 1),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg CV Amount',
          objectNameSingular: 'product',
          aggregateFieldName: 'cvAmount',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: quarter(0, 2),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Total Units Sold',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'quantity',
          aggregateOperation: AggregateOperations.SUM,
          gridPosition: quarter(0, 3),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Products by Category',
          objectNameSingular: 'product',
          groupByFieldName: 'category',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Products by Format',
          objectNameSingular: 'product',
          groupByFieldName: 'format',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(6),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Active vs Inactive Products',
          objectNameSingular: 'product',
          groupByFieldName: 'isActive',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: leftHalf(12),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Commission-Eligible Share',
          objectNameSingular: 'product',
          groupByFieldName: 'commissionEligible',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(12),
        },
        {
          type: 'graph',
          visualization: 'aggregate',
          title: 'Avg Units per Order',
          objectNameSingular: 'xoOrder',
          aggregateFieldName: 'quantity',
          aggregateOperation: AggregateOperations.AVG,
          gridPosition: leftHalf(18),
        },
        {
          type: 'graph',
          visualization: 'pie',
          title: 'Orders by Status',
          objectNameSingular: 'xoOrder',
          groupByFieldName: 'status',
          aggregateFieldName: 'id',
          aggregateOperation: AggregateOperations.COUNT,
          gridPosition: rightHalf(18),
        },
        {
          type: 'recordTable',
          title: 'Products',
          objectNameSingular: 'product',
          gridPosition: fullWidthRow(24),
        },
      ],
    },
  ],
};

// The single "incredible main dashboard" — the global owner/ops command center.
// This is the one we hero in the gallery and surface via primary CTAs.
// All cards are native (no front components required for the core version).
export const PRIMARY_MAIN_DASHBOARD_TEMPLATE = ADMIN_MISSION_CONTROL_I_TEMPLATE;

export const DASHBOARD_TEMPLATES: DashboardTemplate[] = [
  ADMIN_MISSION_CONTROL_I_TEMPLATE,
  ADMIN_MISSION_CONTROL_II_TEMPLATE,
  COMPLIANCE_AND_RISK_TEMPLATE,
  RECRUITING_AND_ONBOARDING_TEMPLATE,
  PRODUCT_PERFORMANCE_TEMPLATE,
  AMBASSADOR_GROWTH_TEMPLATE,
  CUSTOMER_360_TEMPLATE,
  REVENUE_AND_ORDERS_TEMPLATE,
  LIVE_OPERATIONS_TEMPLATE,
];
